#!/bin/bash
HOME=/home/foo
USER=foo
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/bin

ykserial()
{
	export LANG=en_US.UTF-8
	ykman info | grep '^Serial number:' | cut -d: -f2 | tr -dc '[0-9]'
}

get_xscreen()
{
    who | awk 'match($0, /\(:([0-9]+)\)$/) { print substr($0, RSTART, RLENGTH) }' | tr -d '()'
	return $?
}

i3_running()
{
    if [ -z "$(ps aux | grep i3lock | grep -v xautolock | grep -v grep)" ]; then
        echo "inactive"
    else
        echo "active"
    fi
}

lock()
{
	test -d "$HOME/.config/yubikey-hotplug" || return 0
	screen=$(get_xscreen "$USER")
	[ $? -ne 0 ] && return 0
    screensaver_state=`i3_running`
    # handle the switching of yubikey mode
    if [ -z "$(lsusb | grep Yubikey)" ] ; then
        if [ "$screensaver_state" = "active" ]; then
            logger -p kern.info "Yubikey unplugged while $USER's screensaver was active. Everything is cool"
        elif [ "$screensaver_state" = "inactive" -a ! -f "$flag_file" ]; then
            logger -p kern.info "Locking screen for user $USER due to Yubikey disconnect"
            su "$USER" -c "DISPLAY=$screen xautolock -locknow"
        fi
    fi
}

case "$1" in
	disconnect)
		logger -p kern.notice "Yubikey disconnected"
        lock
		;;
	*)
		echo "Usage: $0 disconnect"
		;;
esac
